### ISSUE TITLE
EPIC Paths vs local paths

### ISSUE THREAD

**Issue by mike-jt79** [zenotech/epic-cli#265]
Should the API use an epic specific url to signify a remote location? Something like:
> epiccli cp epic://folder/file ./local_file
> epiccli ls epic://folder/

We could then drop the download/upload options and do it both with cp. I suggest this because I was using cp expecting it to copy to a local folder but was actually making copies in the S3 bucket...

**Comment by jsharpe** [comment]
Would we also want to encode the team into the url somehow so it is clear which team's datastore is being operated on? Do we want to allow copying between different team datastores?

**Comment by mike-jt79** [comment]
I think at the moment we keep the CLI working in a similar way to the web front end, with the team data stores separated totally and the user then switches between team contexts. Maybe have team in the URL as a future enhancement? Printing the current team in the header of the cli output for each command could be useful.
